Reproduce issue with missing RestAPI outputs
Diagnostics:
  aws:apigateway:UsagePlan (usage-plan):
    error: aws:apigateway/usagePlan:UsagePlan resource 'usage-plan' has a problem: Missing required argument: The argument "api_stages.0.api_id" is required, but no definition was found.. Examine values at 'UsagePlan.ApiStages'.
    error: aws:apigateway/usagePlan:UsagePlan resource 'usage-plan' has a problem: Missing required argument: The argument "api_stages.0.stage" is required, but no definition was found.. Examine values at 'UsagePlan.ApiStages'.