Fix missing outputs in all languages (#13)
* Automate simple nodejs integration test

* Reproduce issue with missing RestAPI outputs

Diagnostics:
  aws:apigateway:UsagePlan (usage-plan):
    error: aws:apigateway/usagePlan:UsagePlan resource 'usage-plan' has a problem: Missing required argument: The argument "api_stages.0.api_id" is required, but no definition was found.. Examine values at 'UsagePlan.ApiStages'.
    error: aws:apigateway/usagePlan:UsagePlan resource 'usage-plan' has a problem: Missing required argument: The argument "api_stages.0.stage" is required, but no definition was found.. Examine values at 'UsagePlan.ApiStages'.

* Tentative fix for missing outputs

* Register missing outputs

* Enumerate all output properties

- Without enumerating sub-properties, we just get the id as a string.
- Registering additional outputs is not required.

* Flatten most useful properties as a workaround

- Remove outputting of whole nested resources.

* Revert back to simply outputting the resources

* Try making pulumi packages peer dependencies

- Include as devDependencies too otherwise we can't build.
- Doesn't seem to work from initial testing

* Revert peer-dependency change

* Register missing outputs